management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true

jwt:
  secret: "ClaveSecretaSuperLargaParaFirmarLosTokensJWT_EventosMS_2026_HS256"