server:
  port: 8097

spring:
  application:
    name: ms-participants-service
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ms_participants
    username: root
    password:
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    consumer:
      group-id: participants-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8095/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}