spring:
  application:
    name: ms-pago-service
  config:
    import: optional:configserver:http://root:123456@localhost:7075
  datasource:
    url: jdbc:mysql://localhost:3306/ms_pago
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8097

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8095/eureka
